<?php
/**
 * Created by PhpStorm.
 * User: hyy
 * Date: 2017/11/10
 * Time: 17:30
 */

class Animal
{
    public $name;

    public function bray()
    {
        echo '动物是怎么叫的？';
    }
}

class Cat extends Animal
{
    public function bray()
    {
        Animal::bray(); // TODO: Change the autogenerated stub
        echo 'maoshimiaomiao';
    }
}

class Dog extends Animal
{
    public function bray()
    {
        parent::bray(); // TODO: Change the autogenerated stub
        echo 'goushiwangwang';
    }
}

$bray = new Cat();
$bray->bray();
// 上面输出：动物是怎么叫的？maoshimiaomiao
$call = new Dog();
$call->bray();
// 上面输出：动物是怎么叫的？goushiwangwang